name: Docker Test

on: 
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker container
        run: |
          docker run -d --name testcontainer alpine tail -f /dev/null

      - name: Run tests
        run: |
          docker exec testcontainer /bin/sh -c "
            echo 'Ejecutando pruebas...';
            cd /home;
            mkdir cami;
            cd cami;
            printf 'Este es el contenido del archivo.\nPuede incluir varias lineas.\n' > ejemplo.txt;
            ls -a || exit 1
          "
